name: Cross Info Update

on:
  push:
    branches:
      - main
    paths:
      - 'src/components/namecross/workers.json'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::crossword.r
            any::jsonlite

      - name: Check out repository
        uses: actions/checkout@v3

      - name: update cross info
        run: Rscript cross.r

      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update cross info
